Enhancements for env vars

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,7 +2,7 @@
 # Function File for commonly used Functions
 
 # OSX specific functions
-if [[ `uname` == "Darwin" ]]; then
+if [[ ${Os_Id} == "macos" ]]; then
     2cd() {
       if [[ $# == 0 ]]; then
         builtin cd ~ && ll -tr
@@ -121,29 +121,87 @@ EOF
 fi
 
 # Non OS specific functions
-# Run `dig` and display the most useful info
-digga() {
-  dig +nocmd "$1" any +multiline +noall +answer
-}
+if type -P dig &>/dev/null; then
+    digga() {
+      dig +nocmd "$1" any +multiline +noall +answer
+    }
+fi
 
-docker_destroy() {
-  container=`docker ps | grep $1 | awk '{print $1}'`
-  docker stop $container
-  docker rm $container
-  cowsay $container is stopped and removed
-}
+if type -P docker &>/dev/null; then
+    docker_destroy() {
+      container=`docker ps | grep $1 | awk '{print $1}'`
+      docker stop $container
+      docker rm $container
+      cowsay $container is stopped and removed
+    }
 
-docker_standup() {
-  docker build --tag $1 . && docker run -d --name $1 -p $2:$2 $1
-  cowsay $1 is built and exposed on $2
-}
+    docker_standup() {
+      docker build --tag $1 . && docker run -d --name $1 -p $2:$2 $1
+      cowsay $1 is built and exposed on $2
+    }
+fi
 
-# git config --global alias.magic '!f() { git add -A && git commit -m "$@" && git push; }; f'
-gmagic() {
-   git add --all
-   git commit -am "$*"
-   git push
-}
+if type -P git &>/dev/null; then
+    # git config --global alias.magic '!f() { git add -A && git commit -m "$@" && git push; }; f'
+    gmagic() {
+       git add --all
+       git commit -am "$*"
+       git push
+    }
+
+    # Call from a local repo to open the repository on github/bitbucket in browser
+    # Modified version of https://github.com/zeke/ghwd
+    repo() {
+        # Figure out github repo base URL
+        local base_url
+        base_url=$(git config --get remote.origin.url)
+        base_url=${base_url%\.git} # remove .git from end of string
+
+        # Fix git@github.com: URLs
+        base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
+
+        # Fix git://github.com URLS
+        base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
+
+        # Fix git@bitbucket.org: URLs
+        base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
+
+        # Fix git@gitlab.com: URLs
+        base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
+
+        # Validate that this folder is a git folder
+        if ! git branch 2>/dev/null 1>&2 ; then
+            echo "Not a git repo!"
+            exit $?
+        fi
+
+        # Find current directory relative to .git parent
+        full_path=$(pwd)
+        git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
+        relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
+
+        # If filename argument is present, append it
+        if [ "$1" ]; then
+            relative_path="$relative_path/$1"
+        fi
+
+        # Figure out current git branch
+        # git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+        git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
+
+        # Remove cruft from branchname
+        branch=${git_where#refs\/heads\/}
+
+        [[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
+        url="$base_url/$tree/$branch$relative_path"
+
+
+        echo "Calling $(type open) for $url"
+
+        open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
+    }
+
+fi
 
 goto() {
    tabname $1
@@ -224,58 +282,6 @@ pawk() {
           echo "Running: $cmd"
       fi
       eval $cmd
-}
-
-# Call from a local repo to open the repository on github/bitbucket in browser
-# Modified version of https://github.com/zeke/ghwd
-repo() {
-	# Figure out github repo base URL
-	local base_url
-	base_url=$(git config --get remote.origin.url)
-	base_url=${base_url%\.git} # remove .git from end of string
-
-	# Fix git@github.com: URLs
-	base_url=${base_url//git@github\.com:/https:\/\/github\.com\/}
-
-	# Fix git://github.com URLS
-	base_url=${base_url//git:\/\/github\.com/https:\/\/github\.com\/}
-
-	# Fix git@bitbucket.org: URLs
-	base_url=${base_url//git@bitbucket.org:/https:\/\/bitbucket\.org\/}
-
-	# Fix git@gitlab.com: URLs
-	base_url=${base_url//git@gitlab\.com:/https:\/\/gitlab\.com\/}
-
-	# Validate that this folder is a git folder
-	if ! git branch 2>/dev/null 1>&2 ; then
-		echo "Not a git repo!"
-		exit $?
-	fi
-
-	# Find current directory relative to .git parent
-	full_path=$(pwd)
-	git_base_path=$(cd "./$(git rev-parse --show-cdup)" || exit 1; pwd)
-	relative_path=${full_path#$git_base_path} # remove leading git_base_path from working directory
-
-	# If filename argument is present, append it
-	if [ "$1" ]; then
-		relative_path="$relative_path/$1"
-	fi
-
-	# Figure out current git branch
-	# git_where=$(command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
-	git_where=$(command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
-
-	# Remove cruft from branchname
-	branch=${git_where#refs\/heads\/}
-
-	[[ $base_url == *bitbucket* ]] && tree="src" || tree="tree"
-	url="$base_url/$tree/$branch$relative_path"
-
-
-	echo "Calling $(type open) for $url"
-
-	open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
 }
 
 ssh_setup() {
